### ISSUE TITLE
PrimeFactor алгоритм не работает

### ISSUE THREAD

**Issue by WerNuz** [realkarmakun/CryptoToolsOmsu#1]
В списке простых множителей подаваемого числа не выводится последний (даже если он единственный) простой множитель.

Например, в случае с `20` должен быть массив: ```[2, 2, 5]```
Но алгоритм выводит массив: ```[2, 2]```

Или в случае с `13` должен быть массив: `[13]`
Но алгоритм выводит пустой массив

**Comment by realkarmakun** [comment]
Кажется забыл реализовать вхождение последнего числа в алгоритме. Сейчас проверю.

**Comment by realkarmakun** [comment]
@WerNuz Проверишь на работу? У меня времени нет.

**Comment by WerNuz** [comment]
Работает
